### ISSUE TITLE
Timeout while executing a shell script

### ISSUE THREAD

**Issue by badnetmask** [robmccready/zabbix-isp-speedtest#1]
First of all, this is some great work. Thank you.

I am trying to use your scripts on a Raspberry Pi (Raspbian GNU/Linux 10 (buster)), but bumped into trouble.

```
==> /var/log/zabbix/zabbix_agentd.log <==
 <timestamp> Failed to execute command "/usr/lib/zabbix/externalscripts/isp-speedtest.sh": Timeout while executing a shell script.
```

Running the script in the command line, it takes 25 seconds to complete, so I edited zabbix_agentd.conf and increased the Timeout parameter to 30, but it still fails to run.

Would you have any other suggestion?

**Comment by robmccready** [comment]
Did you restart the agent service after updating the config file? I don't think Zabbix picks up config changes automatically. You might also try a higher timeout (~60sec) to test. There may be some overhead in how Zabbix calls out to scripts. 5sec seems like a lot but it would be worth ruling out.

I did a quick check of the Zabbix code that does shell execute and I don't see any obvious problem that would cause a timeout warning for a non-timeout reason. https://github.com/zabbix/zabbix/blob/37a821d0e3bc5d0a3691277bb444a1507eedfad9/src/libs/zbxexec/execute.c

**Comment by robmccready** [comment]
Random side question. How did you find this repo? I am glad it may be helpful but I can't remember if I ever got around to posting it to the zabbix site or a forum.

**Comment by badnetmask** [comment]
Thank you for your response.
It won't not let me increase the Timeout above 30.
```zabbix_agentd [15360]: wrong value of "Timeout" in config file "/etc/zabbix/zabbix_agentd.conf", line 280```

And I found your repo via Google, searching for "zabbix speed test". Since your repo is public, Google just indexed it.

**Comment by yabdali** [comment]
I had the same problem, apparently, you have to increase the time out to 30 in both the `/etc/zabbix/zabbix_server.conf and /etc/zabbix/zabbix_agentd.conf` then restart both the server and the agent!.

@robmccready Thanks for the awesome template, I wish you can have a graph for upload/download and latency in one shot! Also, it would be of great help to include a parameter for the speed test server ID (the one that usually can be found using --list option) :)

**Comment by robmccready** [comment]
I have some ideas on making the template (or a version of it) that uses atd to avoid the timeouts completely but its a busy week for me so I probably won't be able to play with it right away. https://zabbix.org/wiki/Escaping_timeouts_with_atd

**Comment by robmccready** [comment]
Thanks for the tip on the multiple settings to update.

I can add an all-in-one graph but if the download / upload speeds are too far apart its probably going to be less than ideal. I added a separate issue for it: [#2 Add all-in-one graph](https://github.com/robmccready/zabbix-isp-speedtest/issues/2)

I like the idea of supporting the --server argument. Also separated out into [Support --server command argument #3](https://github.com/robmccready/zabbix-isp-speedtest/issues/3)

> I had the same problem, apparently, you have to increase the time out to 30 in both the `/etc/zabbix/zabbix_server.conf and /etc/zabbix/zabbix_agentd.conf` then restart both the server and the agent!.
> 
> @robmccready Thanks for the awesome template, I wish you can have a graph for upload/download and latency in one shot! Also, it would be of great help to include a parameter for the speed test server ID (the one that usually can be found using --list option) :)

**Comment by badnetmask** [comment]
> I had the same problem, apparently, you have to increase the time out to 30 in both the `/etc/zabbix/zabbix_server.conf and /etc/zabbix/zabbix_agentd.conf` then restart both the server and the agent!.

I tried that, it still doesn't work.

So, my Zabbix server is running on a RaspberryPi, and it's taking 25s to complete a speed test. I tried to run the test on my own laptop, and it takes 18 seconds to complete. That probably means the RPi itself might be a factor here.

After some poking around, I found out that running the "speedtest" script with "--no-pre-allocate" option makes it run 3s faster, bringing down the execution time to 22s, but that's still not enough for Zabbix.

Clearly there's some overhead on the agent which is adding to the total execution time here. I'll keep investigating when I find some free time.

**Comment by yabdali** [comment]
Have you checked the permission on the script `sudo chmod +x script.sh`? Also, have you tried to add the option to have it run for a single connect instead of multiple connections (--single)?

**Comment by badnetmask** [comment]
The permissions are correct. I confirmed the "zabbix" user can run the script as well.
Also, the "--single" option didn't make any difference.

**Comment by yabdali** [comment]
What's the error message? `Timeout while executing a shell script.` or `Get value from agent failed: ZBX_TCP_READ() timed out.`? You mentioned that you tried to run the speedtest from your laptop, have you tried to ssh into your Pi and run the script? If you have tried doing it via ssh on your Pi, have you used speedtest command or the speedtest.sh script?

**Comment by badnetmask** [comment]
The error is "Timeout while executing a shell script.". I measured the speed directly on the Pi, running both the bash script and the speedtest script by itself. Running the speedtest on the laptop, which is on the same network/switch, is 7 seconds faster than running from the Pi (which is the Zabbix server).

**Comment by yabdali** [comment]
"Timeout while executing a shell script." as per my understanding of the Zabbix documentation is due to insufficient timeout set in the agent conf file.  Can you copy and paste the parameters/values for the timeout from the following files?

zabbix_server.conf
zabbix_agentd.conf

**Comment by robmccready** [comment]
I refactored the template/scripts to use atd to avoid timeouts. I have it in a branch right now. Give it a try and let me know if it works for you. https://github.com/robmccready/zabbix-isp-speedtest/tree/dev_v2

The branch also has speedtest server_id support and an all-in-one graph although I like the example yabdali added and I will switch the UI to that when I get a chance.

**Comment by badnetmask** [comment]
I installed everything, then selected "Speedtest Trigger", then "run now", and I don't see any errors.
However the graphs are not being updated, so I selected "Speedtest Results", then "run now", and I get an error:
`Cannot send request: wrong item type.`

**Comment by robmccready** [comment]
The last data for the trigger item will the command (with arguments) that was passed to atd. If you run that from the command line it will give a bit more data on what is happening. The zabbix host name (not the display name) is case sensitive which I ran into. 

Example from my system (scripts are running on zabbix server itself)
Scheduling(now): /usr/lib/zabbix/externalscripts/isp-speedtest-sender.sh 'localhost' '10051' 'Zabbix server' ''

I need to document it better but the way it works is the trigger item crafts a call to the second script and schedules it with atd (for right away). The trigger script returns almost immediately avoiding timeouts. Then asynchronously atd launches a process calling the second script (the sender) which actually runs the speedtest then calls back to the zabbix server using zabbix_sender which is why it needs both zabbix server info (name/port) and the host item name that the speedtest result item exists on.

**Comment by badnetmask** [comment]
I ran the sender script manually, it takes 29s to complete, however I do not see any timeout errors in the logs.

**Comment by badnetmask** [comment]
I think I spoke too soon. There is data in the graphs now.

**Comment by robmccready** [comment]
Have you had any other problems with it in the last week? I have a few more tweaks to finish and I'll probably merge the dev branch to main next week.

**Comment by badnetmask** [comment]
I appreciate the work you've been doing, but I had to rebuild the RPi where Zabbix was running, and haven't got to install it back. It was working fine for a week after the fixes you sent. Since I don't know when the re-install is gonna happen, I think this ticket can be closed, and I would open another one if/when I get an error again.
Thank you very much.

**Comment by robmccready** [comment]
No problem. I'm happy to help. This drove improvements to the template and I learned some more about Zabbix at the same time.
