### ISSUE TITLE
Add all-in-one graph

### ISSUE THREAD

**Issue by robmccready** [robmccready/zabbix-isp-speedtest#2]
Add a graph with upload, download, and latency together

**Comment by yabdali** [comment]
I had a quick fix as per the images below... For the speed test server, I had to hardcode it in the script itself, it would be ideal to set it as a parameter in the template (list of servers available here: [https://c.speedtest.net/speedtest-servers-static.php](url) ) 
It might be worth also creating a trigger for high latency (example: above the average!)

`# Perform speedtest and check exit code
#
SPEEDTEST_OUTPUT=$(speedtest --json --server 4570)`
[zbx_export_templates v2.zip](https://github.com/robmccready/zabbix-isp-speedtest/files/5460471/zbx_export_templates.v2.zip)

![ZBX-SpeedTest-Demo](https://user-images.githubusercontent.com/30695308/97615140-5a449e00-1a34-11eb-8a1e-50b5e12779f9.PNG)

![ZBX-SpeedTest-Graph DvsU](https://user-images.githubusercontent.com/30695308/97615133-57e24400-1a34-11eb-83c5-5bf3a982be55.PNG)

**Comment by badnetmask** [comment]
I like the graph. I also like the idea of a trigger for high latency.

**Comment by robmccready** [comment]
I like the UX on the graph better that the one I put together. I'll update to it.

**Comment by badnetmask** [comment]
Can you please put "Speedtest" in the graph title? Simply "All-in-one" makes it confusing to know what this is about when looking at the list of all the graphs in a host.

**Comment by robmccready** [comment]
Good point. I will add "Speedtest" when I update the UI

**Comment by robmccready** [comment]
Latest commit (a3a6f06) renames All-in-One graph to "Speedtest Summary".

**Comment by robmccready** [comment]
Added latency trigger with commit (03f7d72). default 50ms.
