### ISSUE TITLE
ExternalScripts directive

### ISSUE THREAD

**Issue by aguinaldoabbj** [robmccready/zabbix-isp-speedtest#6]
Dear,
I'm finding a hard time to setup your scripts in my env. In your instructions, you mention to use the ExternalScripts directive in a Zabbix Agent configuration, however, this directive isn't meant to agents, only to zabbix servers. If I put this directive in an agent's conf, the agent daemon fails to start. Am I doing something wrong?
Thanks in advance.

**Comment by robmccready** [comment]
Apologies, this is a documentation bug on my side. I didn't realize at the time but ExternalScripts are only supported on the Zabbix Server or on a Proxy - [External Checks](https://www.zabbix.com/documentation/2.2/manual/config/items/itemtypes/external).

I will update the README to reflect this.

**Comment by robmccready** [comment]
Doc updated with [e21ffa7](https://github.com/robmccready/zabbix-isp-speedtest/commit/e21ffa77542e3a1277baeda63310f627dffa71e1)
