### ISSUE TITLE
There is an error in the template

### ISSUE THREAD

**Issue by magonzalez112** [robmccready/zabbix-isp-speedtest#7]
Everything is working fine. But there is an error in the template. High latency trigger expression.

last(/Template Net ISP Speedtest/net.isp.speedtest.latency,{$SPEEDTEST_TRIGGER_AVG_COUNT})<{$SPEEDTEST_TRIGGER_LATENCY_HIGH}

This should be changed to:
last(/Template Net ISP Speedtest/net.isp.speedtest.latency,{$SPEEDTEST_TRIGGER_AVG_COUNT})>{$SPEEDTEST_TRIGGER_LATENCY_HIGH}

it is an easy fix. I notice because it was complaining about high latency at the very beginning and it was below the value

**Comment by robmccready** [comment]
Thank you for the issue/fix. Apologies for spacing on merging them in for so long. They are in main now with v2.0.5
