### ISSUE TITLE
Error in the SPEEDTEST_TRIGGER_AVG_COUNT default value

### ISSUE THREAD

**Issue by invisibleninja06** [robmccready/zabbix-isp-speedtest#8]
**Problem**
In the file zabbix_isp_speedtest_template.xml the following macro is defined

```
<macro>{$SPEEDTEST_TRIGGER_AVG_COUNT}</macro>
<value>#3</value>
<description>Average last X speedtest runs for trigger values. Avoids alerts on single bad run.</description>
```

Based on false alerts i have seen and the zabbix documentation the pound sign (#) should not be here as the # symbol indicates the last value on the nth value and not and average.

Source: https://www.zabbix.com/documentation/current/en/manual/config/triggers/expression

Expression | Description
-- | --
sum(/host/key,10m) | Sum of values in the last 10 minutes.
sum(/host/key,#10) | Sum of the last ten values.

**Correction**

```
<macro>{$SPEEDTEST_TRIGGER_AVG_COUNT}</macro>
<value>3</value>
<description>Average last X speedtest runs for trigger values. Avoids alerts on single bad run.</description>
```

**Comment by robmccready** [comment]
Thank you. Apologies for spacing out on integrating your fix in for so long
